blog/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('', views.PostView.as_view()),
    path('<int:pk>', views.PostDetail.as_view()),
    path('review/<int:pk>', views.AddComments.as_view(), name='add_comments'),
    path('<int:pk>/add_likes', views.AddLike.as_view(), name='add_likes'),
    path('<int:pk>/del_likes', views.DisLike.as_view(), name='del_likes'),
]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class Post(models.Model):
    '''Данние посте'''
    title = models.CharField('Заголовок записи', max_length=100)
    descriptions = models.TextField('Текст записи')
    author = models.CharField('Имя автора', max_length=100)
    date = models.DateField('Дата публикации')
    img = models.ImageField('Изображение', upload_to='image/%Y')

    def __str__(self):
        return f"{self.title}, {self.author}"

    class Meta:
        verbose_name = 'Запись'
        verbose_name_plural = 'Записи'


class Comments(models.Model):
    '''Коментарий'''
    email = models.EmailField()
    name = models.CharField('Имя', max_length=50)
    text_comments = models.TextField('Текст коментария', max_length=2000)
    post = models.ForeignKey(Post, verbose_name='Публикация', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name}, {self.post}"

    class Meta:
        verbose_name = 'Коментарий'
        verbose_name_plural = 'Коментарии'


class Likes(models.Model):
    '''Лайки'''
    ip = models.CharField('IP-адресс', max_length=100)
    pos = models.ForeignKey(Post, verbose_name='Публикация', on_delete=models.CASCADE)

blog/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import View

from .models import Post, Likes
from .form import CommentsForm


class PostView(View):
    '''Вывод записей'''

    def get(self, request):
        posts = Post.objects.all()
        return render(request, 'blog/blog.html', {'post_list': posts})


class PostDetail(View):
    '''Отдельная страница записей'''

    def get(self, request, pk):
        post = Post.objects.get(id=pk)
        return render(request, 'blog/blog_detail.html', {'post': post})


class AddComments(View):
    '''Добавления коментариев'''

    def post(self, request, pk):
        form = CommentsForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.post_id = pk
            form.save()
        return redirect(f'/{pk}')


def get_client_ip(request):
    '''Возвращает ип клиента с запроса'''
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip


class AddLike(View):
    '''Добавления лайков'''

    def get(self, request, pk):
        ip_client = get_client_ip(request)
        try:
            Likes.objects.get(ip=ip_client, post_id=pk)
            return redirect(f'/{pk}')
        except:
            new_like = Likes()
            new_like.ip = ip_client
            new_like.pos_id = int(pk)
            new_like.save()
            return redirect(f'/{pk}')


class DisLike(View):
    def get(self, request, pk):
        ip_client = get_client_ip(request)
        try:
            like = Likes.objects.filter(ip=ip_client, pos_id=pk).first()
            if like:
                like.delete()
        except Likes.DoesNotExist:
            pass
        return redirect(f'/{pk}')

templates/blog/blog.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Мини - блог</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
   <style>

       body {
            background-color: #f0f0f0;
        }

        a {
            text-decoration: none;
            color: black;
        }


        a:hover {
            color: gray;
        }

    </style>
</head>
<body>
<div class="row d-flex justify-content-center">
  <div class="col-sm-6 mb-3 mb-sm-0 d-flex justify-content-center">
    <div class="card">
      <div class="card-body">
        <a href="/" class="btn btn-dark row d-flex justify-content-center">Главная</a>
        <a href="/admin" class="btn btn-secondary row d-flex justify-content-center">Админ панель</a>
        <br>
        <br>
          <p style="color: black ; font-weight: bold;">ЗАПИСИ</p>

          {% for post in post_list %}
          <div class="card" style="width: 18rem;">
            <a href="{{ post.id }}" >
              <img src="{{ post.img.url  }}" class="card-img-top" alt="...">
              <h4>{{ post.title }} </h4>
            </a>

            <p class="card-text" >{{ post.descriptions }}</p>
            <p class="card-text">{{ post.author }}</p>
          </div>

          {% endfor %}


      </div>
    </div>
  </div>

</div>

templates/blog/blog_detail.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Мини - блог</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
<div class="row d-flex justify-content-center">
  <div class="col-sm-6 mb-3 mb-sm-0">
    <div class="card">
      <div class="card-body">
        <a href="/" class="btn btn-dark">Главная</a>
        <a href="/admin" class="btn btn-secondary">Админ панель</a>
        <br>
        <br>
          <p style="color: black ; font-weight: bold;">
              {{ post.title }}
          </p>
          <p align="center">
            <img src="{{ post.img.url  }}" class="card-img-top" alt="...">
          </p>

          <div class="card" style="width: 100%;">

            <p  class="card-text" >{{ post.descriptions }}</p>
            <p class="card-text">{{ post.author }}</p>
          </div>

          <div>
              <br>
              <p>Понравилось: {{ post.likes_set.all.count }}</p>

              <a class="btn btn-dark" href="{% url 'add_likes' post.id %}">Нравится</a>
              <a class="btn btn-secondary" href="{% url 'del_likes' post.id %}">Не нравится</a>
          </div>

          <div class="mb-3">
                <h3 align="center">Оставить коментарий</h3>
              <form action="{% url 'add_comments' post.id %}" method="post">
                  {% csrf_token %}
                <div class="mb-3">
                    <label  class="form-label">Ваш коментарий:</label>
                    <textarea name="text_comments" class="form-control"  rows="3"></textarea>

                    <br>
                    <label  class="form-label">Ваше Имя*</label>
                    <input type="name" class="form-control"  name="name">

                    <label  class="form-label">Ваш Email*</label>
                    <input type="email" class="form-control"  name="email">
                    <br>
                    <input class="btn btn-dark" type="submit">
                </div>
              </form>
              <hr>

          </div>

          <div>
              {% for comment in post.comments_set.all %}
              <div class="view-comment">
                  <h4>{{ comment.name }}</h4>
                  <p>
                      {{ comment.text_comments }}
                  </p>
              </div>
              {% endfor %}
          </div>

      </div>
    </div>
  </div>

</div>